### ISSUE TITLE
:h quickfix links to cscopequickfix

### ISSUE THREAD

**Issue by dutchgecko** [Herald-Of-Solace/VimHelpBot#10]
Post containing `:help quickfix` resulted in a link to `cscopequickfix`

https://www.reddit.com/r/vim/comments/gzj7pt/onivim_2_v030_alpha_feature_demo/ftgmq30/?context=10000

**Comment by Herald-Of-Solace** [comment]
That comment seems to have been edited. i assume it had some terms containing a help tag that triggered `cscopequickfix`. I tested with a [comment](https://www.reddit.com/r/vim/comments/gq5v0f/vim_help_bot/fthek76?utm_source=share&utm_medium=web2x) and it replied with link to quickfix -
