### ISSUE TITLE
Improve searching

### ISSUE THREAD

**Issue by Herald-Of-Solace** [Herald-Of-Solace/VimHelpBot#2]
Currently the tag search is pretty simple. It searches exact word. But Vim's searching algorithm is pretty sophisticated which can be found in `:h E149`. We should try to replicate the algorithm.

**Comment by Herald-Of-Solace** [comment]
Latest commit implements this.

**Comment by kutsan** [comment]
I think the bot only needs to answer queries with the exact matches. Implementing and maintaining wildcards support will only create more bugs. You should just simply make it exact query only.

**Comment by Herald-Of-Solace** [comment]
I do not want to add `*`, `?` etc wildcard as they are really difficult to manage. But I think partial search support should be there. We can improve on it.
