### ISSUE TITLE
Help pages are shown multiple times if referenced multiple times in the same comment

### ISSUE THREAD

**Issue by rnevius** [Herald-Of-Solace/VimHelpBot#5]
**Describe the bug**

As above.

**To Reproduce**

See: https://www.reddit.com/r/vim/comments/gsaynx/why_are_the_showmode_line_and_the_status_line/fs49kno/

**Expected behavior**

If, for example, I type `:help 'ruler'` in one paragraph and `:help 'ruler'` in another paragraph of the same comment, VimHelpBot should not show help for `'ruler'` twice.

**Screenshots**

<img width="387" alt="Screen Shot 2020-05-28 at 9 11 08 PM" src="https://user-images.githubusercontent.com/4516305/83183304-e110ea00-a127-11ea-8bf8-f98a2fca89d4.png">

**Comment by Herald-Of-Solace** [comment]
This is strange because it already checks for duplicate tags.

**Comment by Herald-Of-Solace** [comment]
Nevermind, the code for checking got deleted during refactoring.
