### ISSUE TITLE
Comments shouldn't be posted when the comment body is empty (no results found)

### ISSUE THREAD

**Issue by rnevius** [Herald-Of-Solace/VimHelpBot#6]
**Describe the bug**

If `:help nonexistent` returns no results, VimHelpBot still posts a comment.

**To Reproduce**

Comment something like `:help :doesnotexist`

**Expected behavior**

No comment is posted.

**Screenshots**

<img width="478" alt="image" src="https://user-images.githubusercontent.com/4516305/83238413-b14cfb00-a196-11ea-8a48-8dee7ac4e3e4.png">

**Additional context**

Seen here: https://www.reddit.com/r/vim/comments/gsojq2/what_is_the_best_way_to_save_resuable_macros/fs6iozj/

**Comment by Herald-Of-Solace** [comment]
https://github.com/Herald-Of-Solace/VimHelpBot/commit/260d26a71162ac5519b2917d17905a5cbafe12b7 should fix this
